# Chicago Payroll Data Exercise Solution

So this Project for Practice <br>
Let's explore real [payroll data of Chicago city](https://www.kaggle.com/chicago/chicago-citywide-payroll-data). This data is available on [kaggle](https://www.kaggle.com) website and can be downloaded using the provided link. 

**I use the Pandas library and NumPy library for EDA exercises and solutions.**

**Links to few similar datasets are given below to explore and practice your skills.**<br>
&#9758; [City payroll information for all Los Angeles employees since 2013](https://www.kaggle.com/cityofLA/city-payroll-data) <br>
&#9758; [San Francisco city employee salary data](https://www.kaggle.com/kaggle/sf-salaries)<br>
&#9758; [New York City - Citywide Payroll Data](https://www.kaggle.com/new-york-city/nyc-citywide-payroll-data)

**1. Import pandas as pd.**

In [1]:
import pandas as pd
import numpy as np

**2. Read City_of_Chicago_Payroll_Data.csv as a dataframe in pay.**

In [2]:
pay = pd.read_csv('City_of_Chicago_Payroll_Data.csv')

**3. Show first five records in your data.**

In [3]:
pay.head() # if i use head it shows only first 5 rows and all columns

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,"$107,790.00",NaN
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,"$104,628.00",NaN
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,"$114,324.00",NaN
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,"$76,932.00",NaN
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,"$111,474.00",NaN

**3. Get the overview of data.<br>**

In [4]:
pay.info() # info() helps full data information like every columns type and count and null

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
dtypes: float64(1), object(7)
memory usage: 2.0+ MB

Notice that:<br>
`All string values shows as Object type` <br>
`Typical Hours` is the only float type. <br>
`Typical Hours`, `Annual Salary` and `Hourly Rate` have lots of NaN or null values.

In [5]:
pay.describe() # this is STD it use for Statistics
# notice that only 1 column shows which is float value

       Typical Hours
count    7883.000000
mean       34.698719
std         9.145553
min        10.000000
25%        20.000000
50%        40.000000
75%        40.000000
max        40.000000

**4. How many 'NaN' you have in each column in your data?**<br>
*Hint: use [<code>isnull()</code>](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.isnull.html)*

In [6]:
pay.isnull()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,False,False,False,False,False,True,False,True
1,False,False,False,False,False,True,False,True
2,False,False,False,False,False,True,False,True
3,False,False,False,False,False,True,False,True
4,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...
32653,False,False,False,False,False,True,False,True
32654,False,False,False,False,False,True,False,True
32655,False,False,False,False,False,True,False,True
32656,False,False,False,False,False,True,False,True
32657,False,False,False,False,False,True,False,True

In [7]:
pay.isnull().sum() # this sum use for total sum for the null values

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        24775
Annual Salary         7883
Hourly Rate          24775
dtype: int64

**5. Output the statistics for your dataset.**

In [10]:
pay.describe(include='all') # if i use all then show all columns in the describe(), else it shows only numeric column

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
count,32658,32658,32658,32658,32658,7883.000000,24775,7883
unique,32350,1095,36,2,2,NaN,1038,167
top,"HERNANDEZ, JUAN C",POLICE OFFICER,POLICE,F,Salary,NaN,"$90,024.00",$35.60
freq,5,9393,12973,30676,24775,NaN,2368,1404
mean,NaN,NaN,NaN,NaN,NaN,34.698719,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,9.145553,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,40.000000,NaN,NaN

**6. What are the maximum, minimum and average Typical Hours? (use 'Typical Hours' column)**<br>

In [13]:
print('Max Typical Hours are:', pay['Typical Hours'].max()) # max value shows from the column
print('Min Typical Hours are:', pay['Typical Hours'].min())
print('Mean/Avg Typical Hours are:', pay['Typical Hours'].mean())

Max Typical Hours are: 40.0
Min Typical Hours are: 10.0
Mean/Avg Typical Hours are: 34.69871876189268

**7. How many employees are on salary and how many are working on hourly basis?**<br>
*Hint: Group the data on 'Salary or Hourly' column. Instead of whole dataset, i can take the single column as input as well.*

In [22]:
#pay.groupby('Salary or Hourly')[['Salary or Hourly']].count() 
pay.groupby('Salary or Hourly')[['Salary or Hourly']].value_counts() # 2ways we can do that

Salary or Hourly
Hourly     7883
Salary    24775
Name: count, dtype: int64

In [23]:
pay.groupby('Salary or Hourly').count()[['Name']]

                   Name
Salary or Hourly
Hourly             7883
Salary            24775

In [24]:
pay['Salary or Hourly'].value_counts()

Salary or Hourly
Salary    24775
Hourly     7883
Name: count, dtype: int64

**8. Which department has maximum no of employees?**

In [29]:
pay['Department'].value_counts().head(1) # first find department then use value_count then use head()

Department
POLICE    12973
Name: count, dtype: int64

In [33]:
pay.groupby('Department')[['Name']].count().idxmax() # idxmax() helps which index has max values it shows top

Name    POLICE
dtype: object

In [35]:
pay.groupby('Department')[['Name']].count().sort_values(by='Name', ascending=False).head(3)

                Name
Department
POLICE         12973
FIRE            4800
STREETS & SAN   2194

**9. How many employees are on Salary and how many are on Hourly in the Police department?**

In [37]:
pay[pay['Department']=='POLICE']['Salary or Hourly'].value_counts()

Salary or Hourly
Salary    12941
Hourly       32
Name: count, dtype: int64

In [38]:
pay[pay['Department'] == 'POLICE'].groupby('Salary or Hourly')[['Salary or Hourly']].count()

                  Salary or Hourly
Salary or Hourly
Hourly                          32
Salary                       12941

In [40]:
df = pay[pay['Department']=='POLICE'] 
df['Salary or Hourly'].value_counts()

Salary or Hourly
Salary    12941
Hourly       32
Name: count, dtype: int64

In [41]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
dtypes: float64(1), object(7)
memory usage: 2.0+ MB

**10. What are the mean, max and min salaries?**<br>
use <code>.str and replace()</code><br>
Create a new column name "Salaries" and separate the number from dollar sign as float .<br>
Hint: [pandas.series.str](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.str.split.html) and [Stackoverflow link](https://stackoverflow.com/questions/38516481/trying-to-remove-commas-and-dollars-signs-with-pandas-in-python)

In [53]:
pay['Salary'] = pay['Annual Salary'].str.replace('$', '') # first create salary column then split '$' sign use : str.replace

In [54]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,"$107,790.00",NaN,"107,790.00"
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,"$104,628.00",NaN,"104,628.00"
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,"$114,324.00",NaN,"114,324.00"
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,"$76,932.00",NaN,"76,932.00"
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,"$111,474.00",NaN,"111,474.00"
...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,"$90,024.00",NaN,"90,024.00"
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,"$48,078.00",NaN,"48,078.00"
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,"$87,006.00",NaN,"87,006.00"
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,"$93,354.00",NaN,"93,354.00"
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,"$115,932.00",NaN,"115,932.00"

In [55]:
pay['Salary'] = pay['Salary'].str.replace(',', '').astype(float) 
# then remove also comma from Salary values use : str.replace(',', '')
# then convert Salary column  string to float use: astype(float)

In [56]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,"$107,790.00",NaN,107790.0
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,"$104,628.00",NaN,104628.0
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,"$114,324.00",NaN,114324.0
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,"$76,932.00",NaN,76932.0
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,"$111,474.00",NaN,111474.0
...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,"$90,024.00",NaN,90024.0
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,"$48,078.00",NaN,48078.0
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,"$87,006.00",NaN,87006.0
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,"$93,354.00",NaN,93354.0
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,"$115,932.00",NaN,115932.0

In [57]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
 8   Salary             24775 non-null  float64
dtypes: float64(2), object(7)
memory usage: 2.2+ MB

In [58]:
print('min Salary :', pay['Salary'].min())
print('max Salary :', pay['Salary'].max())
print('mean Salary :', pay['Salary'].mean())

min Salary : 0.96
max Salary : 300000.0
mean Salary : 87512.78024137235

**11. Find the employee who has the maximum salary.**<br>
Don't use the max number you got above, write a code for general condition. <br>
Try with [<code>idxmax()</code>](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.idxmax.html) as well!

In [73]:
pay[pay['Salary'] == pay['Salary'].max()][['Name', 'Salary']] # use this method for dynamic and smart

                  Name    Salary
8310  EVANS,  GINGER S  300000.0

**12. Find the employee who has the minimum salary.**<br>
Use [<code>idxmin()</code>](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.idxmin.html) as well!

In [74]:
pay[pay['Salary'] == pay['Salary'].min()][['Name', 'Salary']]

                 Name  Salary
15387  KOCH,  STEVEN     0.96

In [75]:
pay['Salary']

0        107790.0
1        104628.0
2        114324.0
3         76932.0
4        111474.0
           ...
32653     90024.0
32654     48078.0
32655     87006.0
32656     93354.0
32657    115932.0
Name: Salary, Length: 32658, dtype: float64

In [76]:
pay['Salary'].idxmin()

15387

In [77]:
pay.iloc[15387]['Name']

'KOCH,  STEVEN '

In [78]:
pay.iloc[pay['Salary'].idxmin()]['Name']

'KOCH,  STEVEN '

In [79]:
pay.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32658 entries, 0 to 32657
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               32658 non-null  object
 1   Job Titles         32658 non-null  object
 2   Department         32658 non-null  object
 3   Full or Part-Time  32658 non-null  object
 4   Salary or Hourly   32658 non-null  object
 5   Typical Hours      7883 non-null   float64
 6   Annual Salary      24775 non-null  object
 7   Hourly Rate        7883 non-null   object
 8   Salary             24775 non-null  float64
dtypes: float64(2), object(7)
memory usage: 2.2+ MB

In [80]:
pay

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary
0,"ALLISON, PAUL W",LIEUTENANT,FIRE,F,Salary,NaN,"$107,790.00",NaN,107790.0
1,"BRUNO, KEVIN D",SERGEANT,POLICE,F,Salary,NaN,"$104,628.00",NaN,104628.0
2,"COOPER, JOHN E",LIEUTENANT-EMT,FIRE,F,Salary,NaN,"$114,324.00",NaN,114324.0
3,"CRESPO, VILMA I",STAFF ASST,LAW,F,Salary,NaN,"$76,932.00",NaN,76932.0
4,"DOLAN, ROBERT J",SERGEANT,POLICE,F,Salary,NaN,"$111,474.00",NaN,111474.0
...,...,...,...,...,...,...,...,...,...
32653,"ZYGOWICZ, PETER J",POLICE OFFICER,POLICE,F,Salary,NaN,"$90,024.00",NaN,90024.0
32654,"ZYLINSKA, KATARZYNA",POLICE OFFICER,POLICE,F,Salary,NaN,"$48,078.00",NaN,48078.0
32655,"ZYMANTAS, MARK E",POLICE OFFICER,POLICE,F,Salary,NaN,"$87,006.00",NaN,87006.0
32656,"ZYRKOWSKI, CARLO E",POLICE OFFICER,POLICE,F,Salary,NaN,"$93,354.00",NaN,93354.0
32657,"ZYSKOWSKI, DARIUSZ",CHIEF DATA BASE ANALYST,DoIT,F,Salary,NaN,"$115,932.00",NaN,115932.0

**13. What are the mean, max and min Hourly Rate?**<br>
use <code>.str and replace()</code><br>
Hint:
Once again, create a new column name "H_Rate" and separate the number from dollar sign as float .<br>

In [81]:
pay['H_Rate']=pay['Hourly Rate'].str.replace('$', '').astype(float)

In [ ]:
pay

In [82]:
print('min H_Rate :', pay['H_Rate'].min())
print('max H_Rate :', pay['H_Rate'].max())
#print('mean H_Rate :', pay['H_Rate'].mean())
print('mean H_Rate :', pay['H_Rate'].mean().round(2))

min H_Rate : 2.65
max H_Rate : 96.0
mean H_Rate : 32.87

**14. How many employees are getting max Hourly Rate?**

In [83]:
pay[pay['H_Rate']==pay['H_Rate'].max()].count()['Name']

np.int64(1)

**15. Who is getting max Hourly Rate?**

In [84]:
pay[pay['H_Rate']==pay['H_Rate'].max()]['Name']

14317    JONES,  JOHN W
Name: Name, dtype: object

In [85]:
pay.iloc[pay['H_Rate'].idxmax()]['Name']

'JONES,  JOHN W'

**16. How many employees are earning less than the average Hourly Rate?**

In [86]:
pay[pay['H_Rate'] < pay['H_Rate'].mean()].count()[['Name']]

Name    2791
dtype: int64

**17. How many employees are paid hourly and they have full-time job?**

In [87]:
pay[(pay['Salary or Hourly']=='Hourly') & (pay['Full or Part-Time']=='F')].count().head(1)

Name    5906
dtype: int64

In [88]:
pay[(pay['Hourly Rate'].notnull()) & (pay['Full or Part-Time']=='F')].count()['Full or Part-Time']

np.int64(5906)

**18. Find the full-time employees who are working at hourly rate of $10.00?**

In [89]:
pay[(pay['Full or Part-Time']=='F') & (pay['H_Rate']==10)] # or (pay['Hourly Rate']=='$10.00')

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate,Salary,H_Rate
1232,"AYALA JR, JESUS",STUDENT INTERN,HUMAN RESOURCES,F,Hourly,35.0,NaN,$10.00,NaN,10.0
4522,"CERVANTES, BIANCA A",STUDENT INTERN,BUDGET & MGMT,F,Hourly,35.0,NaN,$10.00,NaN,10.0
6476,"DAVILA, ROBERTO A",ALDERMANIC AIDE,CITY COUNCIL,F,Hourly,35.0,NaN,$10.00,NaN,10.0
16474,"LEVY, ETHAN",CLERK CITY COUNCIL,CITY COUNCIL,F,Hourly,35.0,NaN,$10.00,NaN,10.0

**19. How many unique Job Titles are there in the data?**

In [90]:
pay['Job Titles'].nunique()

1095

**20. What was the average Salary of the employees in 10 department?**

In [108]:
pay.groupby('Department')[['Salary']].mean().head(10)

                         Salary
Department
ADMIN HEARNG       78912.947368
ANIMAL CONTRL      66089.684211
AVIATION           76140.018777
BOARD OF ELECTION  56051.142857
BOARD OF ETHICS    94552.500000
BUDGET & MGMT      93925.395349
BUILDINGS          98864.833534
BUSINESS AFFAIRS   80446.425000
CITY CLERK         69762.439024
CITY COUNCIL       63577.172069

**21. What is the job title of 'AGAR,  BULENT B'?** please note, there are two spaces between AGAR, and BULENT.

In [94]:
pay[pay['Name']=='AGAR,  BULENT B'][['Job Titles']]

                   Job Titles
230  CHIEF ENGINEER OF SEWERS

In [103]:
name = input("Enter a Name: ")
result = pay[pay['Name']==name][['Job Titles']]
result

Enter a Name:  'AGAR, BULENT B'

Empty DataFrame
Columns: [Job Titles]
Index: []

**22. What are the top most common job titles?**

In [95]:
pay['Job Titles'].value_counts().head(1)

Job Titles
POLICE OFFICER    9393
Name: count, dtype: int64

**23. How many people have the word 'officer' in their job title? (This is pretty tricky)**

In [96]:
def find_string(title):  
    if 'officer' in title.lower(): #Field_Officer(manager) 
        return True
    else:
        return False

In [97]:
pay['Job Titles'].apply(find_string)

0        False
1        False
2        False
3        False
4        False
         ...
32653     True
32654     True
32655     True
32656     True
32657    False
Name: Job Titles, Length: 32658, dtype: bool

In [98]:
pay['Job Titles'].apply(find_string).sum()

np.int64(11101)

In [99]:
sum(pay['Job Titles'].apply(find_string))

11101

In [100]:
pay[pay['Job Titles'].str.contains('officer', case=False)].count()['Name']

np.int64(11101)

In [101]:
sum(pay['Job Titles'].str.contains('officer', case=False)==0)

21557

**24. Save the final dataframe to a csv file**

In [102]:
pay.to_csv('E:\\store.csv')

# Great Job!